version: '3.8'

services:
  yavbot-frontend:
    image: yavbot-frontend:latest
    networks:
      - traefik-public
      - yavbot-networks
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yavbot-frontend.entrypoints=http"
        - "traefik.http.routers.yavbot-frontend.rule=Host(`yavbot-frontend.sistemaagil.net`)"
        - "traefik.http.middlewares.yavbot-frontend-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.yavbot-frontend.middlewares=yavbot-frontend-https-redirect"
        - "traefik.http.routers.yavbot-frontend-secure.entrypoints=https"
        - "traefik.http.routers.yavbot-frontend-secure.rule=Host(`yavbot-frontend.sistemaagil.net`)"
        - "traefik.http.routers.yavbot-frontend-secure.tls=true"
        - "traefik.http.routers.yavbot-frontend-secure.tls.certresolver=http"
        - "traefik.http.routers.yavbot-frontend-secure.service=yavbot-frontend"
        - "traefik.http.services.yavbot-frontend.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"

  yavbot-backend:
    image: yavbot-backend:latest
    networks:
      - yavbot-networks
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yavbot-backend.entrypoints=http"
        - "traefik.http.routers.yavbot-backend.rule=Host(`yavbot-backend.sistemaagil.net`)"
        - "traefik.http.middlewares.yavbot-backend-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.yavbot-backend.middlewares=yavbot-backend-https-redirect"
        - "traefik.http.routers.yavbot-backend-secure.entrypoints=https"
        - "traefik.http.routers.yavbot-backend-secure.rule=Host(`yavbot-backend.sistemaagil.net`)"
        - "traefik.http.routers.yavbot-backend-secure.tls=true"
        - "traefik.http.routers.yavbot-backend-secure.tls.certresolver=http"
        - "traefik.http.routers.yavbot-backend-secure.service=yavbot-backend"
        - "traefik.http.services.yavbot-backend.loadbalancer.server.port=8091"
        - "traefik.docker.network=traefik-public"

  yavbot-db:
    image: postgres:14
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=tdaoybvt
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - yavbot_data:/var/lib/postgresql/data/pgdata
    networks:
      - yavbot-networks
  yavbot_pgadmin:
    image: dpage/pgadmin4:6.11
    environment:
      PGADMIN_DEFAULT_EMAIL: botyavbot@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Yavchat22@
    volumes:
      - pgadmin_yavbot_data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin-yavbot.entrypoints=http"
        - "traefik.http.routers.pgadmin-yavbot.rule=Host(`pgadmin-yavbot.sistemaagil.net`)"
        - "traefik.http.middlewares.pgadmin-yavbot-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pgadmin-yavbot.middlewares=pgadmin-yavbot-https-redirect"
        - "traefik.http.routers.pgadmin-yavbot-secure.entrypoints=https"
        - "traefik.http.routers.pgadmin-yavbot-secure.rule=Host(`pgadmin-yavbot.sistemaagil.net`)"
        - "traefik.http.routers.pgadmin-yavbot-secure.tls=true"
        - "traefik.http.routers.pgadmin-yavbot-secure.tls.certresolver=http"
        - "traefik.http.routers.pgadmin-yavbot-secure.service=pgadmin-yavbot"
        - "traefik.http.services.pgadmin-yavbot.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - yavbot-networks
      - traefik-public
networks:
  traefik-public:
    external: true
  yavbot-networks:
    external: true
volumes:
  yavbot_data:
    external: true
  pgadmin_yavbot_data: 
    external: true